site_name: mifarepy
site_description: "Documentation for the mifarepy project."
site_author: "Spark Drago"
site_url: "https://aarsol-pvt-ltd.github.io/mifarepy/"
repo_url: "https://github.com/AARSOL-Pvt-Ltd/mifarepy/"
repo_name: "mifarepy"
theme:
  name: material
  custom_dir: overrides
  highlightjs: true
  highlight_theme: github  # for light mode
  highlight_theme_dark: dracula  # for dark mode
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
extra_css:
  - style.css
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Examples: examples.md
  - API Reference: api.md
  - Contributing: contributing.md

plugins:
  - git-authors
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: "mifarepy"
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-PZYQH7R8EV
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            opening a <a href="https://github.com/AARSOL-Pvt-Ltd/mifarepy/issues/new?template=feedback.md" target="_blank" rel="noopener">feedback issue</a>.

  version:
    provider: mike