name: Deploy MkDocs Site

on:
  push:
    branches: [ main ]
  # optionally, also on:
  #   tags: [ 'v*.*.*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install mkdocs-material mike

      # 2️⃣ On each new tag (or on every main-branch push), deploy as “latest”
      - name: Deploy new version (latest)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          mike deploy $VERSION latest \
            --update-aliases \
            --branch=gh-pages \
            --remote-name=origin \
            --push
